# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/niel/Projects/ProjectSE/ProjectSE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/niel/Projects/ProjectSE/ProjectSE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/niel/Projects/ProjectSE/ProjectSE/CMakeFiles /home/niel/Projects/ProjectSE/ProjectSE/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/niel/Projects/ProjectSE/ProjectSE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ProjectSE

# Build rule for target.
ProjectSE: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ProjectSE
.PHONY : ProjectSE

# fast build rule for target.
ProjectSE/fast:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/build
.PHONY : ProjectSE/fast

#=============================================================================
# Target rules for targets named ProjectSE_debug

# Build rule for target.
ProjectSE_debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ProjectSE_debug
.PHONY : ProjectSE_debug

# fast build rule for target.
ProjectSE_debug/fast:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/build
.PHONY : ProjectSE_debug/fast

headers/Airplane.o: headers/Airplane.cpp.o

.PHONY : headers/Airplane.o

# target to build an object file
headers/Airplane.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/headers/Airplane.cpp.o
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/headers/Airplane.cpp.o
.PHONY : headers/Airplane.cpp.o

headers/Airplane.i: headers/Airplane.cpp.i

.PHONY : headers/Airplane.i

# target to preprocess a source file
headers/Airplane.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/headers/Airplane.cpp.i
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/headers/Airplane.cpp.i
.PHONY : headers/Airplane.cpp.i

headers/Airplane.s: headers/Airplane.cpp.s

.PHONY : headers/Airplane.s

# target to generate assembly for a file
headers/Airplane.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/headers/Airplane.cpp.s
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/headers/Airplane.cpp.s
.PHONY : headers/Airplane.cpp.s

headers/Airport.o: headers/Airport.cpp.o

.PHONY : headers/Airport.o

# target to build an object file
headers/Airport.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/headers/Airport.cpp.o
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/headers/Airport.cpp.o
.PHONY : headers/Airport.cpp.o

headers/Airport.i: headers/Airport.cpp.i

.PHONY : headers/Airport.i

# target to preprocess a source file
headers/Airport.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/headers/Airport.cpp.i
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/headers/Airport.cpp.i
.PHONY : headers/Airport.cpp.i

headers/Airport.s: headers/Airport.cpp.s

.PHONY : headers/Airport.s

# target to generate assembly for a file
headers/Airport.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/headers/Airport.cpp.s
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/headers/Airport.cpp.s
.PHONY : headers/Airport.cpp.s

headers/Runway.o: headers/Runway.cpp.o

.PHONY : headers/Runway.o

# target to build an object file
headers/Runway.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/headers/Runway.cpp.o
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/headers/Runway.cpp.o
.PHONY : headers/Runway.cpp.o

headers/Runway.i: headers/Runway.cpp.i

.PHONY : headers/Runway.i

# target to preprocess a source file
headers/Runway.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/headers/Runway.cpp.i
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/headers/Runway.cpp.i
.PHONY : headers/Runway.cpp.i

headers/Runway.s: headers/Runway.cpp.s

.PHONY : headers/Runway.s

# target to generate assembly for a file
headers/Runway.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/headers/Runway.cpp.s
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/headers/Runway.cpp.s
.PHONY : headers/Runway.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/main.cpp.s
.PHONY : main.cpp.s

mainTests.o: mainTests.cpp.o

.PHONY : mainTests.o

# target to build an object file
mainTests.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/mainTests.cpp.o
.PHONY : mainTests.cpp.o

mainTests.i: mainTests.cpp.i

.PHONY : mainTests.i

# target to preprocess a source file
mainTests.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/mainTests.cpp.i
.PHONY : mainTests.cpp.i

mainTests.s: mainTests.cpp.s

.PHONY : mainTests.s

# target to generate assembly for a file
mainTests.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/mainTests.cpp.s
.PHONY : mainTests.cpp.s

parsers/Reader.o: parsers/Reader.cpp.o

.PHONY : parsers/Reader.o

# target to build an object file
parsers/Reader.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/parsers/Reader.cpp.o
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/parsers/Reader.cpp.o
.PHONY : parsers/Reader.cpp.o

parsers/Reader.i: parsers/Reader.cpp.i

.PHONY : parsers/Reader.i

# target to preprocess a source file
parsers/Reader.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/parsers/Reader.cpp.i
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/parsers/Reader.cpp.i
.PHONY : parsers/Reader.cpp.i

parsers/Reader.s: parsers/Reader.cpp.s

.PHONY : parsers/Reader.s

# target to generate assembly for a file
parsers/Reader.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/parsers/Reader.cpp.s
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/parsers/Reader.cpp.s
.PHONY : parsers/Reader.cpp.s

parsers/library/tinystr.o: parsers/library/tinystr.cpp.o

.PHONY : parsers/library/tinystr.o

# target to build an object file
parsers/library/tinystr.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/parsers/library/tinystr.cpp.o
.PHONY : parsers/library/tinystr.cpp.o

parsers/library/tinystr.i: parsers/library/tinystr.cpp.i

.PHONY : parsers/library/tinystr.i

# target to preprocess a source file
parsers/library/tinystr.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/parsers/library/tinystr.cpp.i
.PHONY : parsers/library/tinystr.cpp.i

parsers/library/tinystr.s: parsers/library/tinystr.cpp.s

.PHONY : parsers/library/tinystr.s

# target to generate assembly for a file
parsers/library/tinystr.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/parsers/library/tinystr.cpp.s
.PHONY : parsers/library/tinystr.cpp.s

parsers/library/tinyxml.o: parsers/library/tinyxml.cpp.o

.PHONY : parsers/library/tinyxml.o

# target to build an object file
parsers/library/tinyxml.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/parsers/library/tinyxml.cpp.o
.PHONY : parsers/library/tinyxml.cpp.o

parsers/library/tinyxml.i: parsers/library/tinyxml.cpp.i

.PHONY : parsers/library/tinyxml.i

# target to preprocess a source file
parsers/library/tinyxml.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/parsers/library/tinyxml.cpp.i
.PHONY : parsers/library/tinyxml.cpp.i

parsers/library/tinyxml.s: parsers/library/tinyxml.cpp.s

.PHONY : parsers/library/tinyxml.s

# target to generate assembly for a file
parsers/library/tinyxml.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/parsers/library/tinyxml.cpp.s
.PHONY : parsers/library/tinyxml.cpp.s

parsers/library/tinyxmlerror.o: parsers/library/tinyxmlerror.cpp.o

.PHONY : parsers/library/tinyxmlerror.o

# target to build an object file
parsers/library/tinyxmlerror.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/parsers/library/tinyxmlerror.cpp.o
.PHONY : parsers/library/tinyxmlerror.cpp.o

parsers/library/tinyxmlerror.i: parsers/library/tinyxmlerror.cpp.i

.PHONY : parsers/library/tinyxmlerror.i

# target to preprocess a source file
parsers/library/tinyxmlerror.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/parsers/library/tinyxmlerror.cpp.i
.PHONY : parsers/library/tinyxmlerror.cpp.i

parsers/library/tinyxmlerror.s: parsers/library/tinyxmlerror.cpp.s

.PHONY : parsers/library/tinyxmlerror.s

# target to generate assembly for a file
parsers/library/tinyxmlerror.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/parsers/library/tinyxmlerror.cpp.s
.PHONY : parsers/library/tinyxmlerror.cpp.s

parsers/library/tinyxmlparser.o: parsers/library/tinyxmlparser.cpp.o

.PHONY : parsers/library/tinyxmlparser.o

# target to build an object file
parsers/library/tinyxmlparser.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/parsers/library/tinyxmlparser.cpp.o
.PHONY : parsers/library/tinyxmlparser.cpp.o

parsers/library/tinyxmlparser.i: parsers/library/tinyxmlparser.cpp.i

.PHONY : parsers/library/tinyxmlparser.i

# target to preprocess a source file
parsers/library/tinyxmlparser.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/parsers/library/tinyxmlparser.cpp.i
.PHONY : parsers/library/tinyxmlparser.cpp.i

parsers/library/tinyxmlparser.s: parsers/library/tinyxmlparser.cpp.s

.PHONY : parsers/library/tinyxmlparser.s

# target to generate assembly for a file
parsers/library/tinyxmlparser.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/parsers/library/tinyxmlparser.cpp.s
.PHONY : parsers/library/tinyxmlparser.cpp.s

utils.o: utils.cpp.o

.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/utils.cpp.o
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i

.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/utils.cpp.i
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s

.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/utils.cpp.s
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ProjectSE"
	@echo "... ProjectSE_debug"
	@echo "... headers/Airplane.o"
	@echo "... headers/Airplane.i"
	@echo "... headers/Airplane.s"
	@echo "... headers/Airport.o"
	@echo "... headers/Airport.i"
	@echo "... headers/Airport.s"
	@echo "... headers/Runway.o"
	@echo "... headers/Runway.i"
	@echo "... headers/Runway.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainTests.o"
	@echo "... mainTests.i"
	@echo "... mainTests.s"
	@echo "... parsers/Reader.o"
	@echo "... parsers/Reader.i"
	@echo "... parsers/Reader.s"
	@echo "... parsers/library/tinystr.o"
	@echo "... parsers/library/tinystr.i"
	@echo "... parsers/library/tinystr.s"
	@echo "... parsers/library/tinyxml.o"
	@echo "... parsers/library/tinyxml.i"
	@echo "... parsers/library/tinyxml.s"
	@echo "... parsers/library/tinyxmlerror.o"
	@echo "... parsers/library/tinyxmlerror.i"
	@echo "... parsers/library/tinyxmlerror.s"
	@echo "... parsers/library/tinyxmlparser.o"
	@echo "... parsers/library/tinyxmlparser.i"
	@echo "... parsers/library/tinyxmlparser.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

