# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/niel/Projects/ProjectSE/ProjectSE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/niel/Projects/ProjectSE/ProjectSE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/niel/Projects/ProjectSE/ProjectSE/CMakeFiles /home/niel/Projects/ProjectSE/ProjectSE/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/niel/Projects/ProjectSE/ProjectSE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ProjectSE

# Build rule for target.
ProjectSE: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ProjectSE
.PHONY : ProjectSE

# fast build rule for target.
ProjectSE/fast:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/build
.PHONY : ProjectSE/fast

#=============================================================================
# Target rules for targets named ProjectSE_debug

# Build rule for target.
ProjectSE_debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ProjectSE_debug
.PHONY : ProjectSE_debug

# fast build rule for target.
ProjectSE_debug/fast:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/build
.PHONY : ProjectSE_debug/fast

headers/IO/library/tinystr.o: headers/IO/library/tinystr.cpp.o

.PHONY : headers/IO/library/tinystr.o

# target to build an object file
headers/IO/library/tinystr.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/headers/IO/library/tinystr.cpp.o
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/headers/IO/library/tinystr.cpp.o
.PHONY : headers/IO/library/tinystr.cpp.o

headers/IO/library/tinystr.i: headers/IO/library/tinystr.cpp.i

.PHONY : headers/IO/library/tinystr.i

# target to preprocess a source file
headers/IO/library/tinystr.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/headers/IO/library/tinystr.cpp.i
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/headers/IO/library/tinystr.cpp.i
.PHONY : headers/IO/library/tinystr.cpp.i

headers/IO/library/tinystr.s: headers/IO/library/tinystr.cpp.s

.PHONY : headers/IO/library/tinystr.s

# target to generate assembly for a file
headers/IO/library/tinystr.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/headers/IO/library/tinystr.cpp.s
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/headers/IO/library/tinystr.cpp.s
.PHONY : headers/IO/library/tinystr.cpp.s

headers/IO/library/tinyxml.o: headers/IO/library/tinyxml.cpp.o

.PHONY : headers/IO/library/tinyxml.o

# target to build an object file
headers/IO/library/tinyxml.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/headers/IO/library/tinyxml.cpp.o
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/headers/IO/library/tinyxml.cpp.o
.PHONY : headers/IO/library/tinyxml.cpp.o

headers/IO/library/tinyxml.i: headers/IO/library/tinyxml.cpp.i

.PHONY : headers/IO/library/tinyxml.i

# target to preprocess a source file
headers/IO/library/tinyxml.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/headers/IO/library/tinyxml.cpp.i
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/headers/IO/library/tinyxml.cpp.i
.PHONY : headers/IO/library/tinyxml.cpp.i

headers/IO/library/tinyxml.s: headers/IO/library/tinyxml.cpp.s

.PHONY : headers/IO/library/tinyxml.s

# target to generate assembly for a file
headers/IO/library/tinyxml.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/headers/IO/library/tinyxml.cpp.s
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/headers/IO/library/tinyxml.cpp.s
.PHONY : headers/IO/library/tinyxml.cpp.s

headers/IO/library/tinyxmlerror.o: headers/IO/library/tinyxmlerror.cpp.o

.PHONY : headers/IO/library/tinyxmlerror.o

# target to build an object file
headers/IO/library/tinyxmlerror.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/headers/IO/library/tinyxmlerror.cpp.o
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/headers/IO/library/tinyxmlerror.cpp.o
.PHONY : headers/IO/library/tinyxmlerror.cpp.o

headers/IO/library/tinyxmlerror.i: headers/IO/library/tinyxmlerror.cpp.i

.PHONY : headers/IO/library/tinyxmlerror.i

# target to preprocess a source file
headers/IO/library/tinyxmlerror.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/headers/IO/library/tinyxmlerror.cpp.i
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/headers/IO/library/tinyxmlerror.cpp.i
.PHONY : headers/IO/library/tinyxmlerror.cpp.i

headers/IO/library/tinyxmlerror.s: headers/IO/library/tinyxmlerror.cpp.s

.PHONY : headers/IO/library/tinyxmlerror.s

# target to generate assembly for a file
headers/IO/library/tinyxmlerror.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/headers/IO/library/tinyxmlerror.cpp.s
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/headers/IO/library/tinyxmlerror.cpp.s
.PHONY : headers/IO/library/tinyxmlerror.cpp.s

headers/IO/library/tinyxmlparser.o: headers/IO/library/tinyxmlparser.cpp.o

.PHONY : headers/IO/library/tinyxmlparser.o

# target to build an object file
headers/IO/library/tinyxmlparser.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/headers/IO/library/tinyxmlparser.cpp.o
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/headers/IO/library/tinyxmlparser.cpp.o
.PHONY : headers/IO/library/tinyxmlparser.cpp.o

headers/IO/library/tinyxmlparser.i: headers/IO/library/tinyxmlparser.cpp.i

.PHONY : headers/IO/library/tinyxmlparser.i

# target to preprocess a source file
headers/IO/library/tinyxmlparser.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/headers/IO/library/tinyxmlparser.cpp.i
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/headers/IO/library/tinyxmlparser.cpp.i
.PHONY : headers/IO/library/tinyxmlparser.cpp.i

headers/IO/library/tinyxmlparser.s: headers/IO/library/tinyxmlparser.cpp.s

.PHONY : headers/IO/library/tinyxmlparser.s

# target to generate assembly for a file
headers/IO/library/tinyxmlparser.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/headers/IO/library/tinyxmlparser.cpp.s
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/headers/IO/library/tinyxmlparser.cpp.s
.PHONY : headers/IO/library/tinyxmlparser.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/main.cpp.s
.PHONY : main.cpp.s

mainTests.o: mainTests.cpp.o

.PHONY : mainTests.o

# target to build an object file
mainTests.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/mainTests.cpp.o
.PHONY : mainTests.cpp.o

mainTests.i: mainTests.cpp.i

.PHONY : mainTests.i

# target to preprocess a source file
mainTests.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/mainTests.cpp.i
.PHONY : mainTests.cpp.i

mainTests.s: mainTests.cpp.s

.PHONY : mainTests.s

# target to generate assembly for a file
mainTests.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/mainTests.cpp.s
.PHONY : mainTests.cpp.s

other/testfiles/ATCTests.o: other/testfiles/ATCTests.cpp.o

.PHONY : other/testfiles/ATCTests.o

# target to build an object file
other/testfiles/ATCTests.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/ATCTests.cpp.o
.PHONY : other/testfiles/ATCTests.cpp.o

other/testfiles/ATCTests.i: other/testfiles/ATCTests.cpp.i

.PHONY : other/testfiles/ATCTests.i

# target to preprocess a source file
other/testfiles/ATCTests.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/ATCTests.cpp.i
.PHONY : other/testfiles/ATCTests.cpp.i

other/testfiles/ATCTests.s: other/testfiles/ATCTests.cpp.s

.PHONY : other/testfiles/ATCTests.s

# target to generate assembly for a file
other/testfiles/ATCTests.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/ATCTests.cpp.s
.PHONY : other/testfiles/ATCTests.cpp.s

other/testfiles/AirplaneTests.o: other/testfiles/AirplaneTests.cpp.o

.PHONY : other/testfiles/AirplaneTests.o

# target to build an object file
other/testfiles/AirplaneTests.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/AirplaneTests.cpp.o
.PHONY : other/testfiles/AirplaneTests.cpp.o

other/testfiles/AirplaneTests.i: other/testfiles/AirplaneTests.cpp.i

.PHONY : other/testfiles/AirplaneTests.i

# target to preprocess a source file
other/testfiles/AirplaneTests.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/AirplaneTests.cpp.i
.PHONY : other/testfiles/AirplaneTests.cpp.i

other/testfiles/AirplaneTests.s: other/testfiles/AirplaneTests.cpp.s

.PHONY : other/testfiles/AirplaneTests.s

# target to generate assembly for a file
other/testfiles/AirplaneTests.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/AirplaneTests.cpp.s
.PHONY : other/testfiles/AirplaneTests.cpp.s

other/testfiles/AirportOutputTests.o: other/testfiles/AirportOutputTests.cpp.o

.PHONY : other/testfiles/AirportOutputTests.o

# target to build an object file
other/testfiles/AirportOutputTests.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/AirportOutputTests.cpp.o
.PHONY : other/testfiles/AirportOutputTests.cpp.o

other/testfiles/AirportOutputTests.i: other/testfiles/AirportOutputTests.cpp.i

.PHONY : other/testfiles/AirportOutputTests.i

# target to preprocess a source file
other/testfiles/AirportOutputTests.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/AirportOutputTests.cpp.i
.PHONY : other/testfiles/AirportOutputTests.cpp.i

other/testfiles/AirportOutputTests.s: other/testfiles/AirportOutputTests.cpp.s

.PHONY : other/testfiles/AirportOutputTests.s

# target to generate assembly for a file
other/testfiles/AirportOutputTests.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/AirportOutputTests.cpp.s
.PHONY : other/testfiles/AirportOutputTests.cpp.s

other/testfiles/AirportTests.o: other/testfiles/AirportTests.cpp.o

.PHONY : other/testfiles/AirportTests.o

# target to build an object file
other/testfiles/AirportTests.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/AirportTests.cpp.o
.PHONY : other/testfiles/AirportTests.cpp.o

other/testfiles/AirportTests.i: other/testfiles/AirportTests.cpp.i

.PHONY : other/testfiles/AirportTests.i

# target to preprocess a source file
other/testfiles/AirportTests.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/AirportTests.cpp.i
.PHONY : other/testfiles/AirportTests.cpp.i

other/testfiles/AirportTests.s: other/testfiles/AirportTests.cpp.s

.PHONY : other/testfiles/AirportTests.s

# target to generate assembly for a file
other/testfiles/AirportTests.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/AirportTests.cpp.s
.PHONY : other/testfiles/AirportTests.cpp.s

other/testfiles/ApTimeTests.o: other/testfiles/ApTimeTests.cpp.o

.PHONY : other/testfiles/ApTimeTests.o

# target to build an object file
other/testfiles/ApTimeTests.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/ApTimeTests.cpp.o
.PHONY : other/testfiles/ApTimeTests.cpp.o

other/testfiles/ApTimeTests.i: other/testfiles/ApTimeTests.cpp.i

.PHONY : other/testfiles/ApTimeTests.i

# target to preprocess a source file
other/testfiles/ApTimeTests.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/ApTimeTests.cpp.i
.PHONY : other/testfiles/ApTimeTests.cpp.i

other/testfiles/ApTimeTests.s: other/testfiles/ApTimeTests.cpp.s

.PHONY : other/testfiles/ApTimeTests.s

# target to generate assembly for a file
other/testfiles/ApTimeTests.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/ApTimeTests.cpp.s
.PHONY : other/testfiles/ApTimeTests.cpp.s

other/testfiles/GateTests.o: other/testfiles/GateTests.cpp.o

.PHONY : other/testfiles/GateTests.o

# target to build an object file
other/testfiles/GateTests.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/GateTests.cpp.o
.PHONY : other/testfiles/GateTests.cpp.o

other/testfiles/GateTests.i: other/testfiles/GateTests.cpp.i

.PHONY : other/testfiles/GateTests.i

# target to preprocess a source file
other/testfiles/GateTests.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/GateTests.cpp.i
.PHONY : other/testfiles/GateTests.cpp.i

other/testfiles/GateTests.s: other/testfiles/GateTests.cpp.s

.PHONY : other/testfiles/GateTests.s

# target to generate assembly for a file
other/testfiles/GateTests.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/GateTests.cpp.s
.PHONY : other/testfiles/GateTests.cpp.s

other/testfiles/ReaderTest.o: other/testfiles/ReaderTest.cpp.o

.PHONY : other/testfiles/ReaderTest.o

# target to build an object file
other/testfiles/ReaderTest.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/ReaderTest.cpp.o
.PHONY : other/testfiles/ReaderTest.cpp.o

other/testfiles/ReaderTest.i: other/testfiles/ReaderTest.cpp.i

.PHONY : other/testfiles/ReaderTest.i

# target to preprocess a source file
other/testfiles/ReaderTest.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/ReaderTest.cpp.i
.PHONY : other/testfiles/ReaderTest.cpp.i

other/testfiles/ReaderTest.s: other/testfiles/ReaderTest.cpp.s

.PHONY : other/testfiles/ReaderTest.s

# target to generate assembly for a file
other/testfiles/ReaderTest.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/ReaderTest.cpp.s
.PHONY : other/testfiles/ReaderTest.cpp.s

other/testfiles/RunwayTests.o: other/testfiles/RunwayTests.cpp.o

.PHONY : other/testfiles/RunwayTests.o

# target to build an object file
other/testfiles/RunwayTests.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/RunwayTests.cpp.o
.PHONY : other/testfiles/RunwayTests.cpp.o

other/testfiles/RunwayTests.i: other/testfiles/RunwayTests.cpp.i

.PHONY : other/testfiles/RunwayTests.i

# target to preprocess a source file
other/testfiles/RunwayTests.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/RunwayTests.cpp.i
.PHONY : other/testfiles/RunwayTests.cpp.i

other/testfiles/RunwayTests.s: other/testfiles/RunwayTests.cpp.s

.PHONY : other/testfiles/RunwayTests.s

# target to generate assembly for a file
other/testfiles/RunwayTests.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/RunwayTests.cpp.s
.PHONY : other/testfiles/RunwayTests.cpp.s

other/testfiles/SimulatorTests.o: other/testfiles/SimulatorTests.cpp.o

.PHONY : other/testfiles/SimulatorTests.o

# target to build an object file
other/testfiles/SimulatorTests.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/SimulatorTests.cpp.o
.PHONY : other/testfiles/SimulatorTests.cpp.o

other/testfiles/SimulatorTests.i: other/testfiles/SimulatorTests.cpp.i

.PHONY : other/testfiles/SimulatorTests.i

# target to preprocess a source file
other/testfiles/SimulatorTests.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/SimulatorTests.cpp.i
.PHONY : other/testfiles/SimulatorTests.cpp.i

other/testfiles/SimulatorTests.s: other/testfiles/SimulatorTests.cpp.s

.PHONY : other/testfiles/SimulatorTests.s

# target to generate assembly for a file
other/testfiles/SimulatorTests.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/other/testfiles/SimulatorTests.cpp.s
.PHONY : other/testfiles/SimulatorTests.cpp.s

system/ATC.o: system/ATC.cpp.o

.PHONY : system/ATC.o

# target to build an object file
system/ATC.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/ATC.cpp.o
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/ATC.cpp.o
.PHONY : system/ATC.cpp.o

system/ATC.i: system/ATC.cpp.i

.PHONY : system/ATC.i

# target to preprocess a source file
system/ATC.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/ATC.cpp.i
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/ATC.cpp.i
.PHONY : system/ATC.cpp.i

system/ATC.s: system/ATC.cpp.s

.PHONY : system/ATC.s

# target to generate assembly for a file
system/ATC.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/ATC.cpp.s
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/ATC.cpp.s
.PHONY : system/ATC.cpp.s

system/Airplane.o: system/Airplane.cpp.o

.PHONY : system/Airplane.o

# target to build an object file
system/Airplane.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/Airplane.cpp.o
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/Airplane.cpp.o
.PHONY : system/Airplane.cpp.o

system/Airplane.i: system/Airplane.cpp.i

.PHONY : system/Airplane.i

# target to preprocess a source file
system/Airplane.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/Airplane.cpp.i
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/Airplane.cpp.i
.PHONY : system/Airplane.cpp.i

system/Airplane.s: system/Airplane.cpp.s

.PHONY : system/Airplane.s

# target to generate assembly for a file
system/Airplane.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/Airplane.cpp.s
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/Airplane.cpp.s
.PHONY : system/Airplane.cpp.s

system/Airport.o: system/Airport.cpp.o

.PHONY : system/Airport.o

# target to build an object file
system/Airport.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/Airport.cpp.o
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/Airport.cpp.o
.PHONY : system/Airport.cpp.o

system/Airport.i: system/Airport.cpp.i

.PHONY : system/Airport.i

# target to preprocess a source file
system/Airport.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/Airport.cpp.i
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/Airport.cpp.i
.PHONY : system/Airport.cpp.i

system/Airport.s: system/Airport.cpp.s

.PHONY : system/Airport.s

# target to generate assembly for a file
system/Airport.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/Airport.cpp.s
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/Airport.cpp.s
.PHONY : system/Airport.cpp.s

system/AirportExporter.o: system/AirportExporter.cpp.o

.PHONY : system/AirportExporter.o

# target to build an object file
system/AirportExporter.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/AirportExporter.cpp.o
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/AirportExporter.cpp.o
.PHONY : system/AirportExporter.cpp.o

system/AirportExporter.i: system/AirportExporter.cpp.i

.PHONY : system/AirportExporter.i

# target to preprocess a source file
system/AirportExporter.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/AirportExporter.cpp.i
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/AirportExporter.cpp.i
.PHONY : system/AirportExporter.cpp.i

system/AirportExporter.s: system/AirportExporter.cpp.s

.PHONY : system/AirportExporter.s

# target to generate assembly for a file
system/AirportExporter.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/AirportExporter.cpp.s
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/AirportExporter.cpp.s
.PHONY : system/AirportExporter.cpp.s

system/ApTime.o: system/ApTime.cpp.o

.PHONY : system/ApTime.o

# target to build an object file
system/ApTime.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/ApTime.cpp.o
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/ApTime.cpp.o
.PHONY : system/ApTime.cpp.o

system/ApTime.i: system/ApTime.cpp.i

.PHONY : system/ApTime.i

# target to preprocess a source file
system/ApTime.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/ApTime.cpp.i
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/ApTime.cpp.i
.PHONY : system/ApTime.cpp.i

system/ApTime.s: system/ApTime.cpp.s

.PHONY : system/ApTime.s

# target to generate assembly for a file
system/ApTime.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/ApTime.cpp.s
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/ApTime.cpp.s
.PHONY : system/ApTime.cpp.s

system/Gate.o: system/Gate.cpp.o

.PHONY : system/Gate.o

# target to build an object file
system/Gate.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/Gate.cpp.o
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/Gate.cpp.o
.PHONY : system/Gate.cpp.o

system/Gate.i: system/Gate.cpp.i

.PHONY : system/Gate.i

# target to preprocess a source file
system/Gate.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/Gate.cpp.i
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/Gate.cpp.i
.PHONY : system/Gate.cpp.i

system/Gate.s: system/Gate.cpp.s

.PHONY : system/Gate.s

# target to generate assembly for a file
system/Gate.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/Gate.cpp.s
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/Gate.cpp.s
.PHONY : system/Gate.cpp.s

system/Reader.o: system/Reader.cpp.o

.PHONY : system/Reader.o

# target to build an object file
system/Reader.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/Reader.cpp.o
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/Reader.cpp.o
.PHONY : system/Reader.cpp.o

system/Reader.i: system/Reader.cpp.i

.PHONY : system/Reader.i

# target to preprocess a source file
system/Reader.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/Reader.cpp.i
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/Reader.cpp.i
.PHONY : system/Reader.cpp.i

system/Reader.s: system/Reader.cpp.s

.PHONY : system/Reader.s

# target to generate assembly for a file
system/Reader.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/Reader.cpp.s
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/Reader.cpp.s
.PHONY : system/Reader.cpp.s

system/Runway.o: system/Runway.cpp.o

.PHONY : system/Runway.o

# target to build an object file
system/Runway.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/Runway.cpp.o
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/Runway.cpp.o
.PHONY : system/Runway.cpp.o

system/Runway.i: system/Runway.cpp.i

.PHONY : system/Runway.i

# target to preprocess a source file
system/Runway.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/Runway.cpp.i
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/Runway.cpp.i
.PHONY : system/Runway.cpp.i

system/Runway.s: system/Runway.cpp.s

.PHONY : system/Runway.s

# target to generate assembly for a file
system/Runway.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/Runway.cpp.s
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/Runway.cpp.s
.PHONY : system/Runway.cpp.s

system/Simulator.o: system/Simulator.cpp.o

.PHONY : system/Simulator.o

# target to build an object file
system/Simulator.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/Simulator.cpp.o
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/Simulator.cpp.o
.PHONY : system/Simulator.cpp.o

system/Simulator.i: system/Simulator.cpp.i

.PHONY : system/Simulator.i

# target to preprocess a source file
system/Simulator.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/Simulator.cpp.i
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/Simulator.cpp.i
.PHONY : system/Simulator.cpp.i

system/Simulator.s: system/Simulator.cpp.s

.PHONY : system/Simulator.s

# target to generate assembly for a file
system/Simulator.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/Simulator.cpp.s
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/Simulator.cpp.s
.PHONY : system/Simulator.cpp.s

system/utils.o: system/utils.cpp.o

.PHONY : system/utils.o

# target to build an object file
system/utils.cpp.o:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/utils.cpp.o
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/utils.cpp.o
.PHONY : system/utils.cpp.o

system/utils.i: system/utils.cpp.i

.PHONY : system/utils.i

# target to preprocess a source file
system/utils.cpp.i:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/utils.cpp.i
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/utils.cpp.i
.PHONY : system/utils.cpp.i

system/utils.s: system/utils.cpp.s

.PHONY : system/utils.s

# target to generate assembly for a file
system/utils.cpp.s:
	$(MAKE) -f CMakeFiles/ProjectSE.dir/build.make CMakeFiles/ProjectSE.dir/system/utils.cpp.s
	$(MAKE) -f CMakeFiles/ProjectSE_debug.dir/build.make CMakeFiles/ProjectSE_debug.dir/system/utils.cpp.s
.PHONY : system/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ProjectSE"
	@echo "... ProjectSE_debug"
	@echo "... headers/IO/library/tinystr.o"
	@echo "... headers/IO/library/tinystr.i"
	@echo "... headers/IO/library/tinystr.s"
	@echo "... headers/IO/library/tinyxml.o"
	@echo "... headers/IO/library/tinyxml.i"
	@echo "... headers/IO/library/tinyxml.s"
	@echo "... headers/IO/library/tinyxmlerror.o"
	@echo "... headers/IO/library/tinyxmlerror.i"
	@echo "... headers/IO/library/tinyxmlerror.s"
	@echo "... headers/IO/library/tinyxmlparser.o"
	@echo "... headers/IO/library/tinyxmlparser.i"
	@echo "... headers/IO/library/tinyxmlparser.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainTests.o"
	@echo "... mainTests.i"
	@echo "... mainTests.s"
	@echo "... other/testfiles/ATCTests.o"
	@echo "... other/testfiles/ATCTests.i"
	@echo "... other/testfiles/ATCTests.s"
	@echo "... other/testfiles/AirplaneTests.o"
	@echo "... other/testfiles/AirplaneTests.i"
	@echo "... other/testfiles/AirplaneTests.s"
	@echo "... other/testfiles/AirportOutputTests.o"
	@echo "... other/testfiles/AirportOutputTests.i"
	@echo "... other/testfiles/AirportOutputTests.s"
	@echo "... other/testfiles/AirportTests.o"
	@echo "... other/testfiles/AirportTests.i"
	@echo "... other/testfiles/AirportTests.s"
	@echo "... other/testfiles/ApTimeTests.o"
	@echo "... other/testfiles/ApTimeTests.i"
	@echo "... other/testfiles/ApTimeTests.s"
	@echo "... other/testfiles/GateTests.o"
	@echo "... other/testfiles/GateTests.i"
	@echo "... other/testfiles/GateTests.s"
	@echo "... other/testfiles/ReaderTest.o"
	@echo "... other/testfiles/ReaderTest.i"
	@echo "... other/testfiles/ReaderTest.s"
	@echo "... other/testfiles/RunwayTests.o"
	@echo "... other/testfiles/RunwayTests.i"
	@echo "... other/testfiles/RunwayTests.s"
	@echo "... other/testfiles/SimulatorTests.o"
	@echo "... other/testfiles/SimulatorTests.i"
	@echo "... other/testfiles/SimulatorTests.s"
	@echo "... system/ATC.o"
	@echo "... system/ATC.i"
	@echo "... system/ATC.s"
	@echo "... system/Airplane.o"
	@echo "... system/Airplane.i"
	@echo "... system/Airplane.s"
	@echo "... system/Airport.o"
	@echo "... system/Airport.i"
	@echo "... system/Airport.s"
	@echo "... system/AirportExporter.o"
	@echo "... system/AirportExporter.i"
	@echo "... system/AirportExporter.s"
	@echo "... system/ApTime.o"
	@echo "... system/ApTime.i"
	@echo "... system/ApTime.s"
	@echo "... system/Gate.o"
	@echo "... system/Gate.i"
	@echo "... system/Gate.s"
	@echo "... system/Reader.o"
	@echo "... system/Reader.i"
	@echo "... system/Reader.s"
	@echo "... system/Runway.o"
	@echo "... system/Runway.i"
	@echo "... system/Runway.s"
	@echo "... system/Simulator.o"
	@echo "... system/Simulator.i"
	@echo "... system/Simulator.s"
	@echo "... system/utils.o"
	@echo "... system/utils.i"
	@echo "... system/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

